services:
  mongodb:
    image: mongo:4.4
    container_name: chat_mongodb
    ports:
      - '${MONGODB_PORT:-27017}:27017'
    volumes:
      - mongo_data:/data/db
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=${MONGODB_DATABASE:-chat-db}

volumes:
  mongo_data:
